version: "3"

services:
  app:
    build: .
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: adonis-blog-db
